global_exclude_dirs:
    - Ubiquity/annotations
    - docs
    - api
    - documentation

exclude_patterns:
    - Ubiquity/log/chromePhp.php
    - Ubiquity/controllers/Autoloader.php
    - Ubiquity/controllers/admin/UbiquityMyAdminBaseController.php

rules:
    doctrine.database_query_contains_string_and_variable_concatenation:
        enabled: false
    php.use_php_eval_function:
        enabled: false
    php.silenced_error:
        enabled: false
    php.psr1:
        enabled: false
    php.object_parameter_not_type_hinted:
        enabled: false
