<?php
return array(
		"siteUrl"=>"%siteUrl%",
		"documentRoot"=>"%documentRoot%",
		"database"=>[
				"dbName"=>"%dbName%",
				"serverName"=>"%serverName%",
				"port"=>"%port%",
				"user"=>"%user%",
				"password"=>"%password%"
		],
		"onStartup"=>function($action){
		},
		"directories"=>[],
		"templateEngine"=>'micro\views\engine\Twig',
		"templateEngineOptions"=>array("cache"=>false),
		"test"=>false,
		"debug"=>false,
		"di"=>[%injections%]
);
